'use client'
export { ProfileTab } from './ProfileTab'
export { ExperienceTab } from './ExperienceTab'
export { EducationTab } from './EducationTab'
export { QualificationsTab } from './QualificationsTab'
export { SkillsTab } from './SkillsTab'
export { GenerateTab } from './GenerateTab'
export { JobsTab } from './JobsTab'
export { TrackerTab } from './TrackerTab'
export { HistoryTab } from './HistoryTab'
